- name: Add PVE signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://enterprise.proxmox.com/debian/proxmox-release-{{ ansible_distribution_release | lower }}.gpg"
    state: present

- name: Add PVE repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release | lower }} pve-no-subscription"
    state: present

- name: Update
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: full

- name: Install PVE kernel
  become: true
  ansible.builtin.apt:
    name: pve-kernel-6.2
    state: latest

- name: Rebooting host
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 900

- name: Install PVE packages
  become: true
  ansible.builtin.apt:
    name: "{{ pve_packages }}"
    state: latest

- name: Remove Debian kernel and os-prober
  become: true
  ansible.builtin.command:
    cmd: apt-get remove -y linux-image-6.1* os-prober

- name: Remove GRUB zero timeout
  become: true
  ansible.builtin.file:
    path: "/etc/default/grub.d/15_timeout.cfg"
    state: absent
